"""empty message

Revision ID: 2f2315dc622c
Revises: c71be65dc7db
Create Date: 2022-08-20 10:13:30.371501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2315dc622c'
down_revision = 'c71be65dc7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venue_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_artist_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue'], ['id'], ondelete='cascade')
    op.alter_column('Show','id', existing_type=sa.Integer,nullable=False, primary_key=True,  autoincrement=True)
    op.alter_column('Venue','id', existing_type=sa.Integer,nullable=False, primary_key=True,  autoincrement=True)
    op.alter_column('Artist','id',existing_type=sa.Integer,nullable=False, primary_key=True,  autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_artist_fkey', 'Show', 'Artist', ['artist'], ['id'])
    op.create_foreign_key('Show_venue_fkey', 'Show', 'Venue', ['venue'], ['id'])
    # ### end Alembic commands ###
